SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `AtualizadorLBC` ;
CREATE SCHEMA IF NOT EXISTS `AtualizadorLBC` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `AtualizadorLBC` ;

-- -----------------------------------------------------
-- Table `AtualizadorLBC`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AtualizadorLBC`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `login` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
